config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true
  
  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  def self.search(input, id)
    return nil if input == ""
    User.where(['name LIKE ?', "%#{input}%"] ).where.not(id: id).limit(10)
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [] )
  end


  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

      - group.users.each do |user|
        - if current_user.name != user.name
          .chat-group-user.clearfix.js-chat-member
            %input{name: "group[user_ids][]", type: "hidden", value: user.id}
            %p.chat-group-user__name
              = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
              削除 

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'
 

  -# - group.users.each do |user|
  -# - if current_user.name != user.name
  -#   .chat-group-user.clearfix.js-chat-member
  -#     %input{name: "group[user_ids][]", type: "hidden", value: user.id}
  -#     %p.chat-group-user__name
  -#       = user.name
  -#     %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
  -#       削除

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main-chat.html.haml
.main-chat
  .main-chat__header
  link_to
    .main-chat__editbtn
      Edit
    .main-chat__leftbox
      プログラミング
      .main-chat__leftbox-member
        Member : sho-nakao
  .main-chat__footer

app/views/messages/_main_chat.html.haml
.main-chat
  .main-chat__main-header
    .main-chat__main-header__left-box
      = @group.name
      .main-chat__main-header__left-box__inf
        %ul.main-chat__main-header__left-box__inf__member-name
          Member:
          - @group.users.each do |user|
            %li.main-chat__main-header__left-box__inf__member-name
              = user.name
    -# %a{type:"button",class:"main-chat__main-header__edit-btn",link_to:"#"}
    = link_to edit_group_path(@group), class:"main-chat__main-header__edit-btn" do
      Edit

  .messages
    = render @messages
 
  .main-chat__form
    .main-chat__form__form-box
      .main-chat__form__form-box__input-box
        = form_for [@group, @message] do |f|
          .input-box
            = f.text_field :content, class: 'main-chat__form__form-box__input-box__text', placeholder: 'type a message'
            = f.label :image, class: 'main-chat__form__form-box__input-box__text__image' do
              = icon('fas', 'image', class: 'icon')
              = f.file_field :image, class: 'main-chat__form__form-box__input-box__file'
          = f.submit 'Send', class: 'main-chat__form__form-box__submit-btn'

app/views/messages/_message.html.haml
.a__main-content
  .a__main-content__message
    .message{data: {message: {id: message.id}}}
      .a__main-content__message__upper-info
        .a__main-content__message__upper-info__talker
          = message.user.name
        .a__main-content__message__upper-info__date
          = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
      .a__main-content__message__text
        - if message.content.present?
          %p.main-chat__main-content__message__text__content
          = message.content
        = image_tag message.image.url, class: 'main-chat__main-content__message__text__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side-bar
  .side-bar__name
    .side-bar__name__user-box
      %p.side-bar__name__user-box__inf
        中尾翔
      %ul.side-bar__name__user-box__icons
        %li.side-bar__name__user-box__icons__new
          = link_to "#" do
            = icon('fas','edit')
        %li.side-bar__name__user-box__icons__edit
          = link_to "#" do
            = icon('fas','cog')
  .side-bar__groups
    .side-bar__groups__group
      %p.side-bar__groups__group__name
        aaaaa
      %p.side-bar__groups__group__message
        まだメッセージがありません
    .side-bar__groups__group
      %p.side-bar__groups__group__name
        aaaaa
      %p.side-bar__groups__group__message
        まだメッセージがありません

app/views/messages/index.html.haml
.wrapper
  = render "shared/side_bar"
  = render "main_chat"

app/views/shared/_side_bar.html.haml
.side-bar
  .side-bar__name
    .side-bar__name__user-box
      %p.side-bar__name__user-box__inf
        = current_user.name
      %ul.side-bar__name__user-box__icons
        %li.side-bar__name__user-box__icons__new
          = link_to new_group_path do
            = icon('fas','edit')
        %li.side-bar__name__user-box__icons__edit
          = link_to edit_user_path(current_user) do
            = icon('fas','cog')
            
  .side-bar__groups
    - current_user.groups.each do |group|
      .side-bar__groups__group
        = link_to group_messages_path(group) do
          .group
            %p.side-bar__groups__group__name
              = group.name
            %p.side-bar__groups__group__message
              = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'